language: php

env:
  global:
    - SYMFONY__DB_HOST=localhost
    - SYMFONY__DB_PORT=3306
    - SYMFONY__DB_USER=root
    - SYMFONY__DB_PASSWORD=""

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then rm composer.lock; fi;
  - COMPOSER_MEMORY_LIMIT=-1 composer install
  - mysql -e 'CREATE DATABASE modera_notificationsbundle'
