language: php

env:
  global:
    - SYMFONY__db_host=localhost
    - SYMFONY__db_port=3306
    - SYMFONY__db_user=root
    - SYMFONY__db_password=""

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 composer update
  - mysql -e 'CREATE DATABASE modera_notificationsbundle'
