language: php

env:
  global:
    - SYMFONY__db_host=localhost
    - SYMFONY__db_port=3306
    - SYMFONY__db_user=root
    - SYMFONY__db_password=""

php:
  - 5.6
  - 7.0

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE modera_notificationsbundle'
